# golangci-lint config

run:
  timeout: 2m
  skip-dirs:
    - bin
    - vendor

linters:
  disable-all: true
  enable:
    - dupl
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    - unused
    - staticcheck

linters-settings:
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/rafi/gits
  dupl:
    threshold: 400
