---

language: go
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
script:
  - make
before_deploy:
  - make VERSION=${TRAVIS_TAG} release -j2
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: release/*
  file_glob: true
  skip_cleanup: true
  on:
    tags: true
